### ISSUE TITLE
Allow referenced files to be outside of current working directory

### ISSUE THREAD

**Issue by observingClouds** [d70-t/preffs#2]
Most parquet reference files are likely containing relative references, e.g. a `zarr`-file which content is packed in a `car`-file will only reference the `car`-file itself but not the absolute path to the `car` file. The parquet content might look like
```
                      path        offset     size                            raw
key                                                                             
.zattrs     output.001.car  3.382274e+10    706.0                           None
.zgroup                NaN           NaN      NaN  b'{\n    "zarr_format": 2\n}'
.zmetadata  output.001.car  3.382272e+10  14662.0                           None
x/.zarray   output.001.car  3.382272e+10    366.0                           None
x/.zattrs   output.001.car  3.382272e+10    313.0                           None
```
This assumes that the referenced files (here `output.001.car`) are located in the current working directory.

The suggestion would be to provide an optional argument like `prefix` to be able to access referenced files that are not in the current working directory. I imagine something as follows:

```python
import xarray as xr
xr.open_zarr("preffs::example.preffs", storage_options={"prefix":"/path/to/referenced/files/"})
```

**Comment by observingClouds** [comment]
According to the [fsspec documentation](https://filesystem-spec.readthedocs.io/en/latest/features.html?highlight=url%20chaining#url-chaining) additional options to individual protocols are given as additional dictionaries.

In the case of preffs, this could look like
```python
import fsspec
m=fsspec.open("preffs::simplecache::zip://references.preffs::file:///path/to/preffs.zip", preffs={'prefix':"/path/to/referenced/data/"}, simplecache={'cache_storage': '/stored/zip/files'})
```

or as a working example on levante (sry, for not posting a minimal example accessible to everyone):
```python
import fsspec
m=fsspec.open("preffs::zip://EUREC4A_ICON-LES_control_DOM01_RTTOV_gridded.preffs::file:///scratch/m/m300408/tape_archive_index/preffs/preffs.zip", preffs={'prefix':"/scratch/m/m300408/tape_archive_index/to_tape/to_be_validated_for_correct_upload_to_tape/"})
m.fs.car(".zattrs")
```

So I think, PR #3 is actually fixing this issue in the way that we like, I just mis-used `storage_options` in my opening description. With PR #3 applied, the following works:
```python
import xarray as xr
xr.open_zarr("preffs::zip://EUREC4A_ICON-LES_control_DOM01_RTTOV_gridded.preffs::file:///scratch/m/m300408/tape_archive_index/preffs/preffs.zip", storage_options={"preffs":{'prefix':"/scratch/m/m300408/tape_archive_index/to_tape/to_be_validated_for_correct_upload_to_tape/"}})
```

So, I think PR #3 actually does what we want:
- it allows url chaining
- it uses the same methods to pass arguments to the filesystem like e.g. [gcsfs](https://github.com/fsspec/gcsfs/blob/ba716f4667dce9e51bf6454df94dc17a2ff0bd5f/gcsfs/core.py#L233) and [simplecache](https://github.com/fsspec/filesystem_spec/blob/4c5b14000e799d96601c83dfac189bde31f9ce70/fsspec/implementations/cached.py#L46) do
- and most importantly, it fixes this issue

Am I missing something?

**Comment by observingClouds** [comment]
@martindurant you probably know the syntax best! Is my suggestion on how to add a `prefix` to the preffs filesystem the standard/fsspec compatible way?

**Comment by martindurant** [comment]
Yes, it sounds perfectly reasonable - it is an argument which changes how the FS interprets its references, not how it interacts with other FSs in the chain.

In RefernceFileSystem, the intent was, that URLs would be templated, "{{u}}/.xarray", and that the value of the template can be overridden. What you are proposing is nicely simpler than that.

**Comment by observingClouds** [comment]
Thank you @martindurant for your feedback! I very much appreciate it!

@d70-t what do you think? Can we merge #3 ?

**Comment by d70-t** [comment]
As preffs is currently something to explore things, I've merged it. And the solution is elegantly simple :+1:
However, I don't yet see about how we could use the `prefix` method to redirect e.g. references to somewhere inside a `zip` on an `http` resource.

**Comment by observingClouds** [comment]
Oh, now I understand your use case. I haven't thought about this case, but as far as I'm concerned, this should work as well as long as either both the `preffs`-file and the referenced files are at the same level within a `zip` archive or the `preffs`-file contains the relative paths within the zip archive.
I might try this.

**Comment by observingClouds** [comment]
Okay, now that I think more about it, it probably does not work yet the way you like to see it...I'll think about it.
